{BASE_URL: "http://192.168.211.21:8081",
 TOKEN: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVzZXJ0ZXN0MiIsIm9yZ25hbWUiOiJlbnQyIiwiaWF0IjoxNjYwNjEyNjk4LCJleHAiOjE2OTIxNDg2OTh9.JXT6qXSN-HzpDPNReBqbZvUjVcyzUNRLzKWSysfzoGs"
}